syeopite/priviblur

- src/helpers/error_handlers.py
- src/helpers/pool_timeout_tracker.py
- src/jobs/refresh_pool.py
- src/priviblur_extractor/api/api.py
- src/routes/media.py
- src/server.py
https://github.com/syeopite/priviblur/issues/4 appears to be caused by faulty connections that aren't properly released which will result in a PoolTimeout exception when attempting to fetch one.
When enough of a pool gets poisoned, all requests will fail due to the PoolTimeout exceptions.
This commit implements a workaround by detecting and then reinitializing poisoned connection pools which would clear all of the faulty connections.
Closes #4
> Add workaround for poisoned connection pool

- src/templates/blog.jinja
- src/templates/components/blog_contents.jinja
- src/templates/components/timeline.jinja
- src/templates/explore.jinja
- src/templates/search.jinja
- src/templates/tagged.jinja
> Directly show list of posts after clicking on "Next page"

- assets/css/base.css
- assets/css/blog.css
- assets/css/post-layout.css
- assets/js/post.js
- requirements.txt
- src/helpers/ext_npf_renderer.py
- src/helpers/helpers.py
- src/priviblur_extractor/api/api.py
- src/routes/__init__.py
- src/routes/api/__init__.py
- src/routes/api/v1/__init__.py
- src/routes/api/v1/misc.py
- src/routes/blogs.py
- src/routes/explore.py
- src/routes/media.py
- src/routes/search.py
- src/routes/tagged.py
- src/server.py
- src/templates/base.jinja
- src/templates/components/post.jinja
[npf-renderer's next release](https://github.com/syeopite/npf-renderer)  is set to add a bunch of new features such as support for videos (finally) and a new photoset layout system.
Some changes however are needed on Priviblur's side. 
Closes #16
> Update npf-renderer to 0.12.0

- src/routes/blogs.py
This is a bit of a nitpick I found while reading code, but https://priviblur.zangetsu.kaizoku.cyou/owlmond/742708107816370176?fetch_polls=1 doesn't work while https://priviblur.zangetsu.kaizoku.cyou/kaylasartwork/742675030696198144/alert-alert-we-have-an-eris-face-reveal?fetch_polls=1 does
> Fix fetch_polls=1 for slugless URLs

- config.example.toml
- docker-compose.yml
- docker/Dockerfile
Supersede the changes made in #36 
Changes based on https://github.com/PussTheCat-org/docker-priviblur-quay
TL;DR:
- Massively enhance the example config file, dockerfile and the compose file (also make things work OOTB with docker)
Long version:
- config file has been massively enhanced with documentation and now works OOTB with docker (host is now set to "0.0.0.0" by default since it's the standard) - comments "levels" have been standardized with one # for things that can be enabled and 2 for actual comments
- Dockerfile has been redone from basically scratch and optimized in various ways (note: untested with the `COPY` since I clone the whole repo for my image, but you wanted it this way here, so I kept it this way)
- Add some documentation to the compose file (Note the "Taken from" …
> Major enhancement to the docker setup and the config file

- locales/en_US/LC_MESSAGES/priviblur.po
- src/exceptions/error_handlers/_base.py
- src/exceptions/error_handlers/miscellaneous_errors.py
- src/server.py
- src/templates/misc/generic_error.jinja
This commit adds a proper basic fallback error handler that shows debeug information and the context of when the error has occured.
This replaces the default Sanic error handler which does not show any debug information when development mode is off.
The styling for the error handler is very basic and serves as a placeholder until a proper design can be done for it.
This will likely be a v0.3.0 feature rather than v0.1.0 one.
> Add basic fallback error handler

- .github/workflows/release-docker.yml
- README.md
- docker-compose.dev.yml
- docker-compose.yml
I think it would be convenient to have latest images build automatically (so people don't have to build them on their servers), except I think I also should add dev version of a container since releases are quite rare.
This code allows for automatic image build on release.
> Add automatic Docker image build

- docker/Dockerfile
`orjson` is already installed as a musl binary (on amd64 and arm64).
`site-packages` uses the most storage, so a multi-stage build (like copying a venv) doesn't help reduce it further. (Although it would help if you do want to build from source packages)
Fixes #58
> Reduce build dependencies in Dockerfile

- instances.md
removes the trailing slash from the 'priviblur.thebunny.zone' instance as the [regex filter LibRedirect uses](https://github.com/libredirect/instances/blob/a64c19a6b1fa9a0a0d6cca6746bb364435cd7cf9/services/other.py#L213) was detecting it and excluding the instance
> remove trailing slash from instances.md

- src/routes/__init__.py
- src/routes/blogs/__init__.py
- src/routes/blogs/blogs.py
- src/routes/blogs/post.py
- src/server.py
This PR removes the slug check logic from the former route handlers
`_blog_post` and `_blog_post_no_slug`. Replacing this, is a middleware
that handles the slug check logic instead.
By using a middleware, we can apply this logic uniformly to all
additional blog post routes. For example for a post note viewer
ensuring that the endpoints to view post notes always has the correct
slug if applicable, and to remove the given slug if unnecessary.
As the logic that separated the slug and slugless post routes have
been transformed to a single middleware, these two routes have been
merged to use the same handler.
> Use middleware to validate post slugs

- config.example.toml
- src/config/deployment.py
- src/preferences.py
`request.scheme` doesn't work when Priviblur is under a reverse proxy
> Add https config option to enable secure cookies

- config.example.toml
It is incorrect to say to check the locales dir for supported languages as languages have to be explicitly enabled in the `SUPPORTED_LANGUAGES` constant for Priviblur to use it.
> Example config: improve doc for language config

- src/exceptions/error_handlers/miscellaneous_errors.py
- src/routes/assets.py
Usually Priviblur raises a `IsADirectoryError` when one attempts to access `/assets/`
This commit changes that error to show a generic 404 screen.
> Ensure 404 error when accessing /access/ dir

- src/cache/blogs.py
- src/priviblur_extractor/__init__.py
- src/priviblur_extractor/api/api.py
- src/priviblur_extractor/models/base.py
- src/priviblur_extractor/parse/__init__.py
- src/priviblur_extractor/parse/base.py
- src/priviblur_extractor/parse/collection_parsers.py
- src/routes/blogs/blogs.py
- src/templates/blog/base_blog.jinja
- src/templates/blog/blog.jinja
- src/templates/blog/blog_search.jinja
Tumblr switched to continuation tokens for blog search and as such simple page numbers are no longer possible.
Closes #140
> Fix blog search pagination

- src/preferences.py
- src/server.py
Commit ece53025d7f1f9212fc2d8c2cefe14cc7dd536dd introduced a bug where the setting cookie was not getting parsed due to faulty comparison logic (if int == string) and the lack of a proper return causing request.ctx.preferences to become None
Closes #151
> Fix `.replace_from_cookie` logic and usage

- src/routes/blogs/post.py
Tumblr allows for slugs that contain non url safe characters meaning that they will get URL encoded. However, when we compare the given slug against the post's actual slug a correct slug will return a false equality check due to it being URL encoded.
Thus we need to decode the url before comparing
> Decode url-encoded slug before comparing

- src/helpers/helpers.py
A f-string was not following proper 3.11 f-string syntax
> Fix python 3.11 incompatiblity

- src/helpers/helpers.py
- src/priviblur_extractor/parse/items.py
- src/server.py
- src/templates/post/components/header.jinja
On blogs with a custom domain the url given in rebloggedFrom*
and rebloggedRoot* will use their custom domain instead of a
regular tumblr domain.
In order to preserve the slug of the post priviblur uses the url given
from rebloggedFrom* and rebloggedRoot* which meant that users can be
directed to an external site unknowingly.
This PR fixes that by using the url given in the parentPostUrl
which should always be a regular tumblr link. Redundancy is also added
in that priviblur will check if the URL is a Tumblr domain and return
a span if it isn't and priviblur is unable to create a url to the original
post
> Fix reblog attribution link directing to custom domains

- assets/css/base.css
- assets/css/timeline.css
- src/priviblur_extractor/models/__init__.py
- src/priviblur_extractor/models/misc.py
- src/priviblur_extractor/models/timelines.py
- src/priviblur_extractor/parse/collection_parsers.py
- src/priviblur_extractor/parse/items.py
- src/templates/components/signpost.jinja
- src/templates/macros/insert_content_list.jinja
- src/templates/timeline.jinja
Closes #79
This PR fetches and displays Tumblr signpost objects which warns when search results are deemed inappropriate.
In the future Priviblur should parse and template some alert elements based on the contents of the signposts. 
The inappropriate search signposts for example can be turned into two alerts (maybe with a yellow accent color?) for partial restrictions (results are returned sporadically), and full restrictions (results are never returned)
> Add support for Tumblr signpost objects

- src/exceptions/error_handlers/extractor_errors.py
- src/exceptions/error_handlers/miscellaneous_errors.py
- src/helpers/render.py
- src/routes/priviblur/misc.py
- src/routes/settings.py
Also fixes the issue where the current routes using the `render_template` function weren't asynchronous
> Use `render_template` wrapper in all routes

- src/routes/blogs/blogs.py
The merger of #161 had accidentally caused this crucial import to get removed, causing an error on empty search results
> Re-add priviblur_extractor import in blog route

- src/server.py
sanic_ext automatically generate api docs by default. This is unwanted behavior.
> Disable api docs generated by sanic_ext

- instances.md
Adding `pb.cmc.pub` as an instance.
Please let me know if I need to flip the Cloudflare to yes. DNS runs through Cloudflare but proxying is NOT enabled, so it doesn't use Cloudflare's proxy network.
> add pb.cmc.pub

- .github/workflows/priviblur-ci.yml
Split build/test, lint and static locale data gen into three jobs
Fix static locale data regeneration
Ensure lint can pass if static locale data are regenerated
Cache all dependencies installed with all the requirements.txt files
Set fail-fast to false in build/test job
> Overhaul priviblur-ci.yml workflow

- instances.md
Apologies for the quick change from https://github.com/syeopite/priviblur/pull/214, but cmc.pub was getting caught in spam filters/zscaler/etc., so I reverted to cleberg.net, which is my long-standing domain.
Thanks!
> update cmc.pub to cleberg.net

- src/routes/api/v1/misc.py
- src/routes/blogs/__init__.py
Fixes Warning Caused by `\d` as python needs `\\d` for regex.
> fix regex digits warnings
